# Generated by Django 2.0.6 on 2021-01-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=60)),
                ('img', models.ImageField(default='img/1.jpg', upload_to='img')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('age', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': '员工表',
                'verbose_name_plural': '员工表',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=128)),
                ('real_name', models.CharField(max_length=80)),
                ('gender', models.SmallIntegerField(choices=[(1, 'female'), (0, 'male')], default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'bz_user',
            },
        ),
    ]
